before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: github.com/joshuar/autocorrector
    package_name: autocorrector
    replacements:
      amd64: 64-bit
      linux: Linux
    vendor: joshuar
    homepage: https://github.com/joshuar/autocorrector
    maintainer: Joshua Rich <joshua.rich@gmail.com>
    description: Autocorrector is a tool similar to Autokey or AutoHotKey, but targeted mainly at word replacements.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    dependencies:
      - libappindicator-gtk3
    contents:
      - src: init/autocorrector@.service
        dst: /usr/lib/systemd/system/autocorrector@.service
      - src: LICENSE
        dst: /usr/local/share/autocorrector/LICENSE
      - src: README.md
        dst: /usr/local/share/autocorrector/README.md
      - src: configs/corrections.toml
        dst: /usr/local/share/autocorrector/corrections.toml
      - src: assets/icon/autocorrector.png
        dst: /usr/local/share/pixmaps/autocorrector.png
      - src: assets/autocorrector.desktop
        dst: /usr/local/share/applications/autocorrector.desktop
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - configs/corrections.toml
      - init/autocorrector@.service
      - assets/icon/autocorrector.png
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
