before:
  hooks:
    - go mod tidy
    - desktop-file-validate assets/autocorrector.desktop
    # - fyne-cross linux -icon assets/icon/autocorrector.png -release -app-version {{.Version}}

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre:
        - go generate ./...

signs:
- cmd: cosign
  stdin: '{{ .Env.COSIGN_PWD }}'
  args:
  - "sign-blob"
  - "--key=cosign.key"
  - "--output-signature=${signature}"
  - "${artifact}"
  - "--yes" # needed on cosign 2.0.0+
  artifacts: all

archives:
- format: binary

# release:
#   extra_files:
#     - glob: fyne-cross/dist/linux-amd64/go-hass-agent.tar.xz

changelog:
  use: github-native
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - '^docs:'
      - typo

nfpms:
  - id: github.com/joshuar/autocorrector
    package_name: autocorrector
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: joshuar
    homepage: https://github.com/joshuar/autocorrector
    maintainer: Joshua Rich <joshua.rich@gmail.com>
    description: |-
      Autocorrector is a tool similar to Autokey or AutoHotKey, but targeted mainly at word replacements.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        dependencies:
          - libevdev
          - libglvnd-glx
          - libX11
          - libXrandr
          - libXxf86vm
          - libXi
          - libXcursor
          - libXinerama
          - libcap
      deb:
        dependencies:
          - libevdev2
          - libgl1
          - libxi6
          - libxcursor1
          - libxrandr2
          - libxinerama1
          - libcap2
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/autocorrector/LICENSE
      - src: README.md
        dst: /usr/share/doc/autocorrector/README.md
      - src: USAGE.md
        dst: /usr/share/doc/autocorrector/USAGE.md
      - src: configs/corrections.toml
        dst: /usr/share/autocorrector/corrections.toml
      - src: internal/app/assets/icon/autocorrector.png
        dst: /usr/share/pixmaps/autocorrector.png
      - src: assets/autocorrector.desktop
        dst: /usr/share/applications/autocorrector.desktop

    scripts:
      postinstall: tools/postInstall

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
