before:
  hooks:
    - go mod tidy
    - desktop-file-validate assets/autocorrector.desktop
    # - fyne-cross linux -icon assets/icon/autocorrector.png -release -app-version {{.Version}}

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: github.com/joshuar/autocorrector
    package_name: autocorrector
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: joshuar
    homepage: https://github.com/joshuar/autocorrector
    maintainer: Joshua Rich <joshua.rich@gmail.com>
    description: |-
      Autocorrector is a tool similar to Autokey or AutoHotKey, but targeted mainly at word replacements.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        dependencies:
          - libevdev
          - libglvnd-glx
          - libX11
          - libXrandr
          - libXxf86vm
          - libXi
          - libxcursor
          - libXinerama
      deb:
        dependencies:
          - libevdev2
          - libgl1
          - libxi6
          - libxcursor1
          - libxrandr2
          - libxinerama1
    contents:
      - src: init/autocorrector@.service
        dst: /usr/lib/systemd/system/autocorrector@.service
      - src: LICENSE
        dst: /usr/local/share/autocorrector/LICENSE
      - src: README.md
        dst: /usr/local/share/autocorrector/README.md
      - src: USAGE.md
        dst: /usr/local/share/autocorrector/USAGE.md
      - src: configs/corrections.toml
        dst: /usr/local/share/autocorrector/corrections.toml
      - src: assets/icon/autocorrector.png
        dst: /usr/local/share/pixmaps/autocorrector.png
      - src: assets/autocorrector.desktop
        dst: /usr/local/share/applications/autocorrector.desktop

archives:
- format: binary

# release:
#   extra_files:
#     - glob: fyne-cross/dist/linux-amd64/go-hass-agent.tar.xz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - '^docs:'
      - typo
