on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release_please
        name: Run release please
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          fetch-depth: 0

      - name: Install/Cache dependencies
        if: ${{ steps.release_please.outputs.release_created }}
        id: cache_pkg_deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libevdev-dev desktop-file-utils gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Setup Go
        if: ${{ steps.release_please.outputs.release_created }}
        id: setup_go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Update VERSION
        if: ${{ steps.release_please.outputs.release_created }}
        id: update_version
        shell: sh
        run: cd internal/app && printf %s $(git tag | tail -1) > VERSION

      - uses: goreleaser/goreleaser-action@v4
        if: ${{ steps.release_please.outputs.release_created }}
        name: Run Go Releaser
        id: run_goreleaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
